[package]
name = "rust-for-it"
description = "Wait for one or more services to be available before executing a command."
version = "1.3.0"
edition = "2021"
authors = ["Sebastian Pipping <sebastian@pipping.org>"]
license = "MIT"

[dependencies]
anstream = "0.3.2"
clap = { version = "4.3.4", features = ["cargo", "color"] }
indoc = "2.0.1"
lazy_static = "1.4.0"
regex = "1.8.4"
subprocess = "0.2.9"

[profile.release]
# Ideas from https://github.com/johnthagen/min-sized-rust
opt-level = "z"
strip = true
lto = true
codegen-units = 1
