[package]
name = "rust-for-it"
version = "1.0.0"
edition = "2021"
authors = ["Sebastian Pipping <sebastian@pipping.org>"]
license = "MIT"

[dependencies]
clap = "4.3.1"
lazy_static = "1.4.0"
regex = "1.8.3"
subprocess = "0.2.9"
