# This file is part of the rust-for-it project.
#
# Copyright (c) 2023 Sebastian Pipping <sebastian@pipping.org>
# SPDX-License-Identifier: MIT

name: Build and test

on:
  pull_request:
  push:
  schedule:
    - cron: '0 16 * * 5'  # Every Friday 4pm
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-latest]
    runs-on: ${{ matrix.runs-on }}
    env:
      RUSTFLAGS: "-Cinstrument-coverage -D warnings"
    steps:
      - name: Check out
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3

      - name: Build
        run: |-
          set -x

          rustc --version --verbose

          cargo build

      - name: Smoke test CLI
        run: |-
          cargo run
